version: '3'
services:
    mysql:
        container_name: mysql
        restart: always
        image: mysql:latest
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./data:/var/lib/mysql
